[project]
name = "sohun_tpu"
version = "0.0.1"
authors = ["Sohun Patel <sohunpatel@gmail.com"]
license = "MIT"
repository = "https://github.com/sohunpatel/sohun-tpu"

[build]
clock_type = "posedge"
reset_type = "sync_high"
target = {type = "directory", path = "target"}

[format]
indent_width = 4

[test]
simulator = "verilator"
